### ISSUE TITLE
产品添加和产品编辑

### ISSUE THREAD

**Issue by BlowWaterWind** [BlowWaterWind/UCR_UPC#1]
![snip20180626_9](https://user-images.githubusercontent.com/37650269/41911851-66719f72-7980-11e8-9f36-10e5202d4942.png)
产品编辑
```css
.tj-sx .tj-con li {
    float: left;
    padding-right: 25px;
}
```

![snip20180626_7](https://user-images.githubusercontent.com/37650269/41911855-690b1b8c-7980-11e8-8666-91d0cae40d0a.png)
产品添加的样式

```css
.tj-sy .tj-con li {
    float: inherit !important;
}
```
